### ISSUE TITLE
COG rendered incorrectly

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-layer#8]
I'm trying to render https://raw.githubusercontent.com/cholmes/pdd-stac/beta2/disasters/hurricane-harvey/hurricane-harvey-0831/20170831_172754_101c/20170831_172754_101c.json, but it seems there is some distortion taking place:

![image](https://user-images.githubusercontent.com/8262166/132233317-fee97084-4962-405d-9366-f43be043ef73.png)

**Comment by m-mohr** [comment]
By the way, this was working flawlessly for quite some time, but I think after one of the georaster-layer-for-leaflet releases this got broken...

**Comment by DanielJDufour** [comment]
I'm wondering if this is an issue related to https://github.com/GeoTIFF/georaster-layer-for-leaflet/issues/75 and https://github.com/GeoTIFF/georaster-layer-for-leaflet/issues/74, which were both fixed by the newest release of georaster-layer-for-leaflet.  Would you be able to uninstall and reinstall stac-layer and see if that fixes the problem?

**Comment by m-mohr** [comment]
It seems to be fixed in at least v0.4.2 as far as I can tell. Thanks!
